namespace: techprober
name: minio
version: 1.0.4
readme: README.md
authors:
- Kevin Yu <kevinyu211@yahoo.com>
- Shi Kun <kunish.butt@gmail.com>
- TechProber <techprober@protonmail.com>
description: ansible collection for minio related operations
license_file: 'LICENSE'
tags:
  - techprober
  - linux
  - minio
dependencies: {}
repository: http://github.com/techprober/galaxy-collections
documentation: https://github.com/techprober/galaxy-collections/tree/master/collections/minio
homepage: https://github.com/techprober/galaxy-collections/tree/master/collections/minio
issues: http://github.com/techprober/galaxy-collections/issues
build_ignore: []
