namespace: techprober
name: minio
version: 1.0.0
readme: README.md
authors:
- Kevin Yu <kevinyu211@yahoo.com>
- Shi Kun <kunish.butt@gmail.com>
- TechProber <techprober@protonmail.com>
description: ansible collection for minio related operations
license_file: 'LICENSE'
tags:
  - techprober
  - linux
  - minio
dependencies: {}
repository: http://github.com/techprober/cloud-estate
documentation: http://github.com/techprober/cloud-estate/tree/master/ansible-playbooks/collections/minio/README.md
homepage: http://github.com/techprober
issues: http://github.com/techprober/cloud-estate
build_ignore: []
