---
- name: Backup data to minio bucket
  command: "{{ ansible_env.HOME }}/backup.sh"
  register: result
  become: true
  become_user: "{{ ansible_user }}"

- name: Check if backup job has completed successfully
  ansible.builtin.debug:
    msg: "Backup ran successfully!"
  when: result is changed
