---
- name: Update package source list
  apt:
    update_cache: yes
  become: yes

- name: Install base packages defined in the list
  ansible.builtin.apt:
    pkg: "{{ base_packages }}"
  become: yes

- name: Install user-defined extra packages
  ansible.builtin.apt:
    pkg: "{{ extra_packages }}"
  become: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: yes
